# Define director mapping and genres
director_mapping = {
    'Frank Darabont': 41,
    'Francis Ford Coppola': 39,
    'Christopher Nolan': 18,
    'Sidney Lumet': 127,
    'Steven Spielberg': 132,
    'Peter Jackson': 107,
    'Quentin Tarantino': 109,
    'Sergio Leone': 125,
    'Robert Zemeckis': 117,
    'David Fincher': 26,
    'Irvin Kershner': 57,
    'Lana Wachowski': 79,
    'Martin Scorsese': 88,
    'Milos Forman': 96,
    'Denis Villeneuve': 31,
    'Frank Capra': 40,
    'Akira Kurosawa': 2,
    'Jonathan Demme': 74,
    'Fernando Meirelles': 36,
    'Roberto Benigni': 118,
    'James Cameron': 59,
    'George Lucas': 44,
    'Hayao Miyazaki': 54,
    'Roman Polanski': 120,
    'Bong Joon Ho': 10,
    'Alfred Hitchcock': 4,
    'Joaquim Dos Santos': 64,
    'Ridley Scott': 113,
    'Roger Allers': 119,
    'Luc Besson': 83,
    'Tony Kaye': 143,
    'Damien Chazelle': 22,
    'Isao Takahata': 58,
    'Masaki Kobayashi': 89,
    'Bryan Singer': 13,
    'Michael Curtiz': 93,
    'Olivier Nakache': 101,
    'Giuseppe Tornatore': 48,
    'Charles Chaplin': 17,
    'Vidhu Vinod Chopra': 145,
    'Andrew Stanton': 5,
    'Florian Henckel von Donnersmarck': 37,
    'Billy Wilder': 8,
    'Stanley Kubrick': 130,
    'Anthony Russo': 6,
    'Bob Persichetti': 9,
    'Sam Mendes': 123,
    'Park Chan-wook': 103,
    'Lee Unkrich': 81,
    'John Lasseter': 70,
    'Wolfgang Petersen': 151,
    'Mel Gibson': 91,
    'Todd Phillips': 141,
    'Gus Van Sant': 51,
    'Makoto Shinkai': 86,
    'Rajkumar Hirani': 110,
    'Stanley Donen': 128,
    'Nadine Labaki': 97,
    'Darren Aronofsky': 25,
    'Elem Klimov': 32,
    'Richard Marquand': 112,
    'Michel Gondry': 95,
    'Thomas Vinterberg': 140,
    'David Lean': 27,
    'Orson Welles': 102,
    'Fritz Lang': 42,
    'Brian De Palma': 12,
    'Jean-Pierre Jeunet': 62,
    'Michael Mann': 94,
    'Pete Docter': 105,
    'Robert Mulligan': 115,
    'George Roy Hill': 46,
    'Asghar Farhadi': 7,
    'John McTiernan': 71,
    'Aamir Khan': 0,
    'Guy Ritchie': 52,
    'Thomas Kail': 139,
    'Curtis Hanson': 21,
    'Vittorio De Sica': 146,
    'Oliver Hirschbiegel': 99,
    'Nitesh Tiwari': 98,
    'Peter Farrelly': 106,
    'Florian Zeller': 38,
    'Stanley Kramer': 129,
    'Joseph L. Mankiewicz': 76,
    'Peter Weir': 108,
    'Joseph Kosinski': 75,
    'Paul Thomas Anderson': 104,
    'M. Night Shyamalan': 84,
    'Guillermo del Toro': 50,
    'Clint Eastwood': 19,
    'Ethan Coen': 35,
    'Ron Howard': 122,
    'John Carpenter': 66,
    'John Huston': 69,
    'Terry Gilliam': 138,
    'John Sturges': 72,
    'David Lynch': 28,
    'Victor Fleming': 144,
    'James McTeigue': 61,
    'Juan José Campanella': 77,
    'Martin McDonagh': 87,
    'Danny Boyle': 24,
    'Joel Coen': 65,
    'Jon Watts': 73,
    'Sergio Pablos': 126,
    'Gavin O"Connor': 43,
    'Takashi Yamazaki': 135,
    'David Yates': 29,
    'Majid Majidi': 85,
    'Steve McQueen': 131,
    'Richard Linklater': 111,
    'William Wyler': 149,
    'Wes Anderson': 147,
    'Jim Sheridan': 63,
    'Damián Szifron': 23,
    'George Miller': 45,
    'Clyde Bruckman': 20,
    'Michael Cimino': 92,
    'Elia Kazan': 33,
    'Buster Keaton': 14,
    'Carol Reed': 16,
    'Henri-Georges Clouzot': 55,
    'Dean DeBlois': 30,
    'Ingmar Bergman': 56,
    'Adam Elliot': 1,
    'Brad Bird': 11,
    'James Mangold': 60,
    'Yasujirô Ozu': 152,
    'Lenny Abrahamson': 82,
    'John G. Avildsen': 68,
    'Tom McCarthy': 142,
    'Terry George': 137,
    'Oliver Stone': 100,
    'Carl Theodor Dreyer': 15,
    'Mathieu Kassovitz': 90,
    'Gore Verbinski': 49,
    'William Friedkin': 148,
    'T.J. Gnanavel': 134,
    'Rob Reiner': 114,
    'Lasse Hallström': 80,
    'Sean Penn': 124,
    'Çagan Irmak': 153,
    'Robert Wise': 116,
    'John Ford': 67,
    'Ernst Lubitsch': 34,
    'Gillo Pontecorvo': 47,
    'Harold Ramis': 53,
    'Alejandro G. Iñárritu': 3,
    'Stuart Rosenberg': 133,
    'Tate Taylor': 136,
    'Ron Clements': 121,
    'Kevin Costner': 78,
    'Wim Wenders': 150
}

genres = [
    'Action', 'Adventure', 'Animation', 'Biography', 'Comedy',
    'Crime', 'Drama', 'Family', 'Fantasy', 'Film-Noir',
    'History', 'Horror', 'Music', 'Musical', 'Mystery',
    'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War', 'Western'
]